from pathlib import Path

import pandas as pd
import plotly.express as px
import streamlit as st


ROOT_DIR = Path(__file__).resolve().parents[1]

DEFAULT_SIMULATION_PATH = ROOT_DIR / "data" / "processed" / "wc2026_simulation.csv"
DEFAULT_METRICS_PATH = ROOT_DIR / "data" / "processed" / "metrics.csv"


st.set_page_config(
    page_title="WC 2026 ML Simulator Dashboard",
    page_icon="⚽",
    layout="wide",
)


@st.cache_data
def load_csv(path: str) -> pd.DataFrame:
    return pd.read_csv(path)


def detect_probability_columns(df: pd.DataFrame) -> list[str]:
    probability_keywords = [
        "prob",
        "probability",
        "qual",
        "r16",
        "qf",
        "sf",
        "final",
        "win",
    ]

    probability_columns = []

    for column in df.columns:
        column_lower = column.lower()

        if column_lower in ["team", "country"]:
            continue

        if any(keyword in column_lower for keyword in probability_keywords):
            if pd.api.types.is_numeric_dtype(df[column]):
                probability_columns.append(column)

    return probability_columns


def format_probability(value: float) -> str:
    if pd.isna(value):
        return "n/a"

    if value <= 1:
        return f"{value * 100:.1f}%"

    return f"{value:.1f}%"


def probability_to_percent(series: pd.Series) -> pd.Series:
    if series.dropna().max() <= 1:
        return series * 100

    return series


def main() -> None:
    st.title("⚽ WC 2026 ML Simulator Dashboard")

    st.markdown(
        """
        This dashboard explores the Monte Carlo simulation results generated by the
        WC 2026 ML Simulator. Select a team to inspect its probability of reaching
        each stage of the tournament.
        """
    )

    with st.sidebar:
        st.header("Dashboard settings")

        simulation_path = st.text_input(
            "Simulation results file",
            value=str(DEFAULT_SIMULATION_PATH),
        )

        metrics_path = st.text_input(
            "Model metrics file",
            value=str(DEFAULT_METRICS_PATH),
        )

    try:
        results = load_csv(simulation_path)
    except Exception as error:
        st.error(f"Could not load simulation results: {error}")
        st.stop()

    results.columns = [column.strip() for column in results.columns]

    if "team" not in results.columns:
        possible_team_columns = ["Team", "country", "Country", "team_name"]

        for column in possible_team_columns:
            if column in results.columns:
                results = results.rename(columns={column: "team"})
                break

    if "team" not in results.columns:
        st.error("The simulation file must contain a `team` column.")
        st.stop()

    probability_columns = detect_probability_columns(results)

    if not probability_columns:
        st.error(
            "No probability columns were detected. Expected columns such as "
            "`win_prob`, `final_prob`, `sf_prob`, `qf_prob`, `r16_prob`, or `qual_prob`."
        )
        st.stop()

    default_metric = "win_prob" if "win_prob" in probability_columns else probability_columns[0]

    selected_metric = st.sidebar.selectbox(
        "Ranking metric",
        probability_columns,
        index=probability_columns.index(default_metric),
    )

    selected_team = st.sidebar.selectbox(
        "Select a team",
        sorted(results["team"].dropna().unique()),
    )

    top_n = st.sidebar.slider(
        "Number of teams displayed",
        min_value=5,
        max_value=min(30, len(results)),
        value=min(10, len(results)),
    )

    overview_tab, team_tab, models_tab, data_tab = st.tabs(
        ["Overview", "Team profile", "Model metrics", "Raw data"]
    )

    with overview_tab:
        st.subheader("Tournament overview")

        ranked = results.sort_values(selected_metric, ascending=False).copy()
        ranked[f"{selected_metric}_percent"] = probability_to_percent(ranked[selected_metric])

        best_team = ranked.iloc[0]
        selected_row = results.loc[results["team"] == selected_team].iloc[0]

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                label=f"Highest {selected_metric}",
                value=best_team["team"],
                delta=format_probability(best_team[selected_metric]),
            )

        with col2:
            st.metric(
                label=f"{selected_team} — {selected_metric}",
                value=format_probability(selected_row[selected_metric]),
            )

        with col3:
            st.metric(
                label="Teams in simulation",
                value=len(results),
            )

        fig = px.bar(
            ranked.head(top_n),
            x=f"{selected_metric}_percent",
            y="team",
            orientation="h",
            title=f"Top {top_n} teams by {selected_metric}",
            labels={
                f"{selected_metric}_percent": "Probability (%)",
                "team": "Team",
            },
        )

        fig.update_layout(yaxis={"categoryorder": "total ascending"})

        st.plotly_chart(fig, use_container_width=True)

        st.dataframe(
            ranked[["team"] + probability_columns],
            use_container_width=True,
            hide_index=True,
        )

    with team_tab:
        st.subheader(f"Team profile: {selected_team}")

        selected_row = results.loc[results["team"] == selected_team].iloc[0]

        metric_columns = st.columns(min(4, len(probability_columns)))

        for index, column in enumerate(probability_columns):
            with metric_columns[index % len(metric_columns)]:
                st.metric(column, format_probability(selected_row[column]))

        team_probabilities = pd.DataFrame(
            {
                "Stage": probability_columns,
                "Probability": [selected_row[column] for column in probability_columns],
            }
        )

        team_probabilities["Probability (%)"] = probability_to_percent(
            team_probabilities["Probability"]
        )

        fig_team = px.bar(
            team_probabilities,
            x="Stage",
            y="Probability (%)",
            title=f"Stage probabilities for {selected_team}",
        )

        st.plotly_chart(fig_team, use_container_width=True)

    with models_tab:
        st.subheader("Model benchmark")

        try:
            metrics = load_csv(metrics_path)
            st.dataframe(metrics, use_container_width=True, hide_index=True)

            numeric_columns = [
                column
                for column in metrics.columns
                if pd.api.types.is_numeric_dtype(metrics[column])
            ]

            if numeric_columns:
                metric_to_plot = st.selectbox("Metric to plot", numeric_columns)

                model_column = "model" if "model" in metrics.columns else metrics.columns[0]

                fig_metrics = px.bar(
                    metrics,
                    x=model_column,
                    y=metric_to_plot,
                    title=f"Model comparison — {metric_to_plot}",
                )

                st.plotly_chart(fig_metrics, use_container_width=True)

        except Exception:
            st.warning("No metrics file found. Run the evaluation pipeline first.")

    with data_tab:
        st.subheader("Raw simulation results")

        st.dataframe(results, use_container_width=True, hide_index=True)

        csv = results.to_csv(index=False).encode("utf-8")

        st.download_button(
            label="Download simulation results as CSV",
            data=csv,
            file_name="wc2026_simulation_dashboard_export.csv",
            mime="text/csv",
        )


if __name__ == "__main__":
    main()
