import joblib
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

ROOT_DIR = Path(__file__).resolve().parents[1]

# Chemins par défaut
DEFAULT_SIMULATION_PATH = ROOT_DIR / "data" / "processed" / "wc2026_simulation.csv"
DEFAULT_METRICS_PATH = ROOT_DIR / "data" / "processed" / "metrics.csv"
DEFAULT_MODEL_PATH = ROOT_DIR / "data" / "processed" / "models" / "champion_xgboost.pkl"

# Ordre chronologique idéal des colonnes de probabilités
CHRONOLOGICAL_STAGES = ["qual", "r16", "qf", "sf", "final", "win"]


st.set_page_config(
    page_title="WC 2026 ML Simulator Dashboard",
    page_icon="⚽",
    layout="wide",
)


# --- CACHING & CHARGEMENT ---


@st.cache_data
def load_csv(path: str) -> pd.DataFrame:
    return pd.read_csv(path)


@st.cache_resource
def load_ml_model(path: str):
    return joblib.load(path)


# --- UTILITAIRES DATA ---


def standardize_columns(df: pd.DataFrame) -> pd.DataFrame:
    df.columns = df.columns.str.lower().str.strip()
    if "team" not in df.columns:
        possible_team_columns = ["team_name", "country", "nation"]
        for col in possible_team_columns:
            if col in df.columns:
                df = df.rename(columns={col: "team"})
                break
    return df


def detect_probability_columns(df: pd.DataFrame) -> list[str]:
    probability_keywords = [
        "prob",
        "probability",
        "qual",
        "r16",
        "qf",
        "sf",
        "final",
        "win",
    ]
    detected = []
    for column in df.columns:
        if column == "team":
            continue
        if any(keyword in column for keyword in probability_keywords):
            if pd.api.types.is_numeric_dtype(df[column]):
                detected.append(column)

    sorted_cols = []
    for stage in CHRONOLOGICAL_STAGES:
        for col in detected:
            if stage in col and col not in sorted_cols:
                sorted_cols.append(col)

    for col in detected:
        if col not in sorted_cols:
            sorted_cols.append(col)

    return sorted_cols


def format_probability(value: float) -> str:
    if pd.isna(value):
        return "n/a"
    if value <= 1:
        return f"{value * 100:.1f}%"
    return f"{value:.1f}%"


def probability_to_percent(series: pd.Series) -> pd.Series:
    if series.dropna().max() <= 1:
        return series * 100
    return series


def clean_feature_name(name: str) -> str:
    if "__" in name:
        name = name.split("__", 1)[1]
    return name.replace("_", " ").title()


def oklch_approx_to_hex(l, c, h_deg):
    h = h_deg / 360
    s = min(c * 2.5, 1.0)
    r, g, b = colorsys.hls_to_rgb(h, l, s)
    return f"#{int(r*255):02x}{int(g*255):02x}{int(b*255):02x}"


# --- VIZ: FEATURE IMPORTANCE ---


def create_feature_importance_plot(model):
    # Extraction pipeline
    if hasattr(model, "calibrated_classifiers_"):
        first_fold = model.calibrated_classifiers_[0].estimator
    else:
        first_fold = model

    preprocessor = first_fold.steps[0][1]
    xgb_model = first_fold.steps[-1][1]

    try:
        feature_names = preprocessor.get_feature_names_out()
    except Exception:
        feature_names = [
            f"feature_{i}" for i in range(len(xgb_model.feature_importances_))
        ]

    importances = xgb_model.feature_importances_
    min_len = min(len(feature_names), len(importances))

    # Création du DataFrame
    df_imp = (
        pd.DataFrame(
            {
                "Feature": [clean_feature_name(f) for f in feature_names[:min_len]],
                "Importance": importances[:min_len],
            }
        )
        .sort_values("Importance", ascending=False)
        .head(20)
        .sort_values("Importance", ascending=True)
    )

    # Ajout d'une hauteur fixe (height=650) pour laisser de la place aux 20 variables
    fig = px.bar(
        df_imp,
        x="Importance",
        y="Feature",
        orientation="h",
        title="Top 20 Feature Importances (XGBoost)",
        labels={"Importance": "Gain moyen normalisé", "Feature": "Variable"},
        height=650,
    )

    fig.update_layout(xaxis_showgrid=False, yaxis_showgrid=False)

    fig.update_yaxes(dtick=1, automargin=True)

    return fig


# --- APP PRINCIPALE ---


def main() -> None:
    st.title("WC 2026 ML Simulator Dashboard")

    st.markdown("""
        This dashboard explores the Monte Carlo simulation results generated by the
        WC 2026 ML Simulator. Select a team to inspect its probability of reaching
        each stage of the tournament.
        """)

    with st.sidebar:
        st.header("Dashboard settings")

        with st.expander("⚙️ Advanced Settings"):
            simulation_path = st.text_input(
                "Simulation results file", value=str(DEFAULT_SIMULATION_PATH)
            )
            metrics_path = st.text_input(
                "Model metrics file", value=str(DEFAULT_METRICS_PATH)
            )
            model_path = st.text_input(
                "Champion model (.pkl)", value=str(DEFAULT_MODEL_PATH)
            )

    try:
        raw_results = load_csv(simulation_path)
    except Exception as error:
        st.error(f"Could not load simulation results: {error}")
        st.stop()

    results = standardize_columns(raw_results)

    if "team" not in results.columns:
        st.error("The simulation file must contain a `team` column.")
        st.stop()

    probability_columns = detect_probability_columns(results)

    if not probability_columns:
        st.error("No probability columns were detected.")
        st.stop()

    default_metric = (
        "win_prob" if "win_prob" in probability_columns else probability_columns[-1]
    )

    selected_metric = st.sidebar.selectbox(
        "Ranking metric",
        probability_columns,
        index=probability_columns.index(default_metric),
    )

    selected_team = st.sidebar.selectbox(
        "Select a team",
        sorted(results["team"].dropna().unique()),
    )

    top_n = st.sidebar.slider(
        "Number of teams displayed",
        min_value=5,
        max_value=min(30, len(results)),
        value=min(10, len(results)),
    )

    overview_tab, team_tab, models_tab, data_tab = st.tabs(
        ["Overview", "Team profile", "Model metrics & Explainability", "Raw data"]
    )

    with overview_tab:
        st.subheader("Tournament overview")

        ranked = results.sort_values(selected_metric, ascending=False).copy()
        for col in probability_columns:
            ranked[col] = probability_to_percent(ranked[col])

        best_team = ranked.iloc[0]
        second_best_team = ranked.iloc[1] if len(ranked) > 1 else None
        selected_row = results.loc[results["team"] == selected_team].iloc[0]

        if second_best_team is not None:
            st.info(
                f"💡 According to the model, **{best_team['team'].title()}** is the favorite for the `{selected_metric}` metric with a **{best_team[selected_metric]:.1f}%** chance, followed by **{second_best_team['team'].title()}** ({second_best_team[selected_metric]:.1f}%)."
            )

        col1, col2, col3 = st.columns(3)

        with col1:
            st.metric(
                f"Highest {selected_metric}",
                best_team["team"].title(),
                f"{best_team[selected_metric]:.1f}%",
            )
        with col2:
            st.metric(
                f"{selected_team.title()} — {selected_metric}",
                format_probability(selected_row[selected_metric]),
            )
        with col3:
            st.metric("Teams in simulation", len(results))

        plot_df = ranked.head(top_n).copy()
        fig = px.bar(
            plot_df,
            x=selected_metric,
            y="team",
            orientation="h",
            title=f"Top {top_n} teams by {selected_metric}",
            labels={selected_metric: "Probability (%)", "team": "Team"},
        )
        fig.update_layout(yaxis={"categoryorder": "total ascending"})
        st.plotly_chart(fig, use_container_width=True)

        column_config = {"team": st.column_config.TextColumn("Team")}
        for col in probability_columns:
            column_config[col] = st.column_config.ProgressColumn(
                col.replace("_", " ").title(),
                help=f"Probability for {col}",
                format="%.1f%%",
                min_value=0,
                max_value=100,
            )

        st.dataframe(
            ranked[["team"] + probability_columns],
            use_container_width=True,
            hide_index=True,
            column_config=column_config,
        )

    with team_tab:
        st.subheader(f"Team profile: {selected_team.title()}")
        selected_row = results.loc[results["team"] == selected_team].iloc[0]

        metric_columns = st.columns(min(4, len(probability_columns)))
        for index, column in enumerate(probability_columns):
            with metric_columns[index % len(metric_columns)]:
                st.metric(
                    column.replace("_", " ").title(),
                    format_probability(selected_row[column]),
                )

        team_probabilities = pd.DataFrame(
            {
                "Stage": [c.replace("_", " ").title() for c in probability_columns],
                "Probability": [selected_row[column] for column in probability_columns],
            }
        )
        team_probabilities["Probability (%)"] = probability_to_percent(
            team_probabilities["Probability"]
        )

        fig_team = px.funnel(
            team_probabilities,
            x="Probability (%)",
            y="Stage",
            title=f"Tournament progression probabilities for {selected_team.title()}",
        )
        fig_team.update_traces(textinfo="value+percent initial")
        st.plotly_chart(fig_team, use_container_width=True)

    with models_tab:
        st.subheader("Model benchmark")

        try:
            metrics = load_csv(metrics_path)
            st.dataframe(metrics, use_container_width=True, hide_index=True)

            numeric_columns = [
                col
                for col in metrics.columns
                if pd.api.types.is_numeric_dtype(metrics[col])
            ]
            if numeric_columns:
                metric_to_plot = st.selectbox("Metric to plot", numeric_columns)
                model_column = (
                    "model" if "model" in metrics.columns else metrics.columns[0]
                )
                fig_metrics = px.bar(
                    metrics,
                    x=model_column,
                    y=metric_to_plot,
                    title=f"Model comparison — {metric_to_plot}",
                )
                st.plotly_chart(fig_metrics, use_container_width=True)
        except Exception:
            st.warning("No metrics file found. Run the evaluation pipeline first.")

        st.markdown("---")
        st.subheader("Explainability (Feature Importance)")

        try:
            # On charge le modèle en utilisant notre fonction avec le cache
            ml_model = load_ml_model(model_path)

            # On génère et affiche le graphe
            fig_importance = create_feature_importance_plot(ml_model)
            st.plotly_chart(fig_importance, use_container_width=True)
        except Exception as e:
            st.error(
                f"Impossible de charger le modèle ou de générer les Feature Importances : {e}"
            )
            st.info(
                "💡 Vérifie que le fichier .pkl est bien présent dans le dossier 'models/'."
            )

    with data_tab:
        st.subheader("Raw simulation results")
        st.dataframe(raw_results, use_container_width=True, hide_index=True)
        csv = raw_results.to_csv(index=False).encode("utf-8")
        st.download_button(
            "Download simulation results as CSV",
            csv,
            "wc2026_simulation_dashboard_export.csv",
            "text/csv",
        )


if __name__ == "__main__":
    main()
